### ISSUE TITLE
Support deb archives using Zstd compression

### ISSUE THREAD

**Issue by lalten** [psigen/rules_debian#5]
https://github.com/psigen/rules_debian/blob/ee393a9af48fda437cdc8021b6cacc89b160c363/debian.bzl#L175
Ubuntu Jammy libopencv-dev (http://archive.ubuntu.com/ubuntu/pool/universe/o/opencv/libopencv-dev_4.5.4+dfsg-9ubuntu4_amd64.deb) does not have a `data.tar.xz`,it has a `data.tar.zst`

**Comment by psigen** [comment]
Should be closed by #7
